esphome:
  name: prana
  friendly_name: prana


esp32:
  board: esp32dev
  framework: # Strongly recommended to use IDF framework instead of arduino. 
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: <your key>

ota:
  platform: esphome
  password: <your password>

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Prana Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

# MAC address can be obtained via "BLE Scanner" app on your smartphone or BLE Client Tracker component
# TODO: try to merge it with "prana_ble"
# TODO: make option to add by device name?
ble_client:
  - mac_address: 00:A0:50:00:00:03
    id: prana

prana_ble:
  id: prana_client
  ble_client_id: prana

# voltage and frequency sensors seems only available for old devices with 220V fans
sensor:
  - platform: prana_ble
    prana_ble_id: prana_client
    voltage:
      name: "Prana voltage"
    frequency:
      name: "Prana frequency"

switch:
  - platform: prana_ble
    prana_ble_id: prana_client
    connect: # Switch to turn off BLE connection between recuperator and ESP32. Useful if you want to connect from native smartphone app
      name: prana_connect
      restore_mode: ALWAYS_ON
    enable: # turn on/off the device
      id: enable
      name: prana_enable
    heating: # turn on/off internal heating element
      id: heating
      name: prana_heating
    winter_mode:  # turn on/off "winter" mode
      name: prana_winter_mode
    auto_mode:  # turn on/off "auto" mode. Untested.
      name: prana_auto_mode

# TODO: make option to control in/out fans. For now only controlling both fans available.
fan:
  - platform: prana_ble
    prana_ble_id: prana_client
    name: prana_fan

external_components:
  - source: https://github.com/voed/prana_ble@main
    components: [prana_ble]
    refresh: 1min
